<a href="https://colab.research.google.com/github/Aahra/E-commerce-dataset/blob/main/Ecommerce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

order1 = "https://raw.githubusercontent.com/Aahra/E-commerce-dataset/main/Dataset/orders.csv"
order = pd.read_csv(order1, parse_dates=["order_date"])
print(order.shape)

(12480, 9)

In [2]:
display(order.head())

,order_id,customer_id,product_id,category,brand,price,quantity,order_date,city
0,ORD10001,CUST042,PRD017,Electronics,Boat,1299.0,1,2024-01-01,Mumbai
1,ORD10002,CUST119,PRD221,Fashion,Levis,2199.0,1,2024-01-01,Mumbai
2,ORD10003,CUST042,PRD088,Home & Kitchen,Milton,649.0,2,2024-01-02,Mumbai
3,ORD10004,CUST311,PRD500,Electronics,Samsung,18999.0,1,2024-01-02,Mumbai
4,ORD10005,CUST008,PRD156,Beauty,Lakme,399.0,3,2024-01-02,Bengaluru

In [3]:
print(pd.__version__)

2.2.3

In [4]:
customers ="https://raw.githubusercontent.com/Aahra/E-commerce-dataset/main/Dataset/customers.csv"
customer = pd.read_csv(customers,parse_dates=["signup_date"])
print(customer.shape)

(1500, 5)

In [5]:
products1="https://raw.githubusercontent.com/Aahra/E-commerce-dataset/main/Dataset/products.csv"
product= pd.read_csv(products1)
print(product.shape)

(600, 8)

In [6]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12480 entries, 0 to 12479
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     12480 non-null  object
 1   customer_id  12480 non-null  object
 2   product_id   12480 non-null  object
 3   category     12480 non-null  object
 4   brand        12360 non-null  object
 5   price        12480 non-null  float64
 6   quantity     12480 non-null  int64
 7   order_date   12480 non-null  datetime64[ns]
 8   city         12480 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 877.6+ KB

In [8]:
order[["price","quantity"]].describe()

              price      quantity
count  12480.000000  12480.000000
mean    1274.489744      1.663381
std     1728.344159      1.144670
min      149.000000      1.000000
25%      440.000000      1.000000
50%      776.000000      1.000000
75%     1555.000000      2.000000
max    18999.000000      8.000000